create extension if not exists pgcrypto;
create table if not exists public.students(id uuid primary key default gen_random_uuid(),full_name text not null,email text not null,phone text not null,education text,program text not null,created_at timestamptz default now());
create table if not exists public.updates(id bigint generated by default as identity primary key,title text not null,text text not null,created_at timestamptz default now());
create table if not exists public.events(id bigint generated by default as identity primary key,title text not null,date date not null,text text,created_at timestamptz default now());
create table if not exists public.gallery(id bigint generated by default as identity primary key,title text not null,image text not null,created_at timestamptz default now());
alter table public.students enable row level security; alter table public.updates enable row level security; alter table public.events enable row level security; alter table public.gallery enable row level security;
create policy "public enrollment insert" on public.students for insert to anon,authenticated with check(true);
create policy "public updates read" on public.updates for select to anon,authenticated using(true);
create policy "public events read" on public.events for select to anon,authenticated using(true);
create policy "public gallery read" on public.gallery for select to anon,authenticated using(true);
insert into storage.buckets(id,name,public) values('academy-images','academy-images',true) on conflict(id) do nothing;
create policy "public academy images read" on storage.objects for select using(bucket_id='academy-images');
-- For production, add authenticated admin-only INSERT/UPDATE/DELETE policies for events, updates, gallery and storage.objects.
